### ISSUE TITLE
no default features for actix-web

### ISSUE THREAD

**Issue by robjtede** [kardeiz/actix-flash#1]
If/when the actix-web dependency is updated to v3, the dependency in Cargo.toml should ideally be:

```diff
- actix-web = "3.0.2"
+ actix-web = { version = "3.0.2", default-features = false }
```

**Comment by kardeiz** [comment]
Thanks! I've updated to actix-web v3 in [`actix-flash 0.2.0`](https://crates.io/crates/actix-flash/0.2.0) (with `v2` available as a feature) and specified no default features for the actix-web dependency as suggested. 

I had to make a change to how the flash values are serialized, since actix-web v3 now uses the `cookie` crate, which strips out quotation marks around the cookie value (which were meaningful here). There are now some unnecessary characters in the cookie value. I've been using `serde_json` for this de/serialization, just because probably everyone has it, but it might be better to use a more compact format (which would also resolve this issue).

**Comment by robjtede** [comment]
Nice job updating and keeping v2 support. 👍

I can't say I've used this crate so not sure what changes were make, anyway using serde_json is a good idea since it is standard and doesn't add deps. Didn't know that this behavior had changed but glad you found a fix.
